feat(docs): update docs-generator workflow
prepare処理をreusable workflowの中に含める

diff --git a/.github/workflows/docs-generator.yml b/.github/workflows/docs-generator.yml
--- a/.github/workflows/docs-generator.yml
+++ b/.github/workflows/docs-generator.yml
@@ -1,23 +1,30 @@
-# アクション／Reusable Workflowsのドキュメントを自動生成する
-#  @see https://zenn.dev/tmknom/books/pragmatic-composite-action/viewer/docs
-#  @see https://zenn.dev/tmknom/articles/actdocs-github-actions
-#  @see https://github.com/tmknom/docs-workflows/blob/main/.github/workflows/composite-action.yml
-#  @see https://github.com/tmknom/git-push-action/blob/main/action.yml
-
 name: Generate Documentation
 
 on:
   workflow_call:
     inputs:
-      yaml-files:
+      doc-type:
         description: |
-          A JSON array of YAML file paths for documentation generation.
+          Type of documentation to generate: workflow or composite.
         type: string
         required: true
+        default: "workflow"
 
-      markdown-files:
+      # yaml-files:
+      #   description: |
+      #     A JSON array of YAML file paths for documentation generation.
+      #   type: string
+      #   required: true
+
+      # markdown-files:
+      #   description: |
+      #     A JSON array of Markdown file paths where documentation should be injected.
+      #   type: string
+      #   required: true
+
+      commit-message:
         description: |
-          A JSON array of Markdown file paths where documentation should be injected.
+          The commit message.
         type: string
         required: true
 
@@ -27,15 +34,9 @@ on:
         type: string
         required: false
 
-      commit-message:
-        description: |
-          The commit message.
-        type: string
-        required: true
-
     outputs:
       branch:
-        value: ${{ jobs.generate.outputs.branch }}
+        value: ${{ jobs.prepare-and-generate.outputs.branch }}
         description: Name of the pushed branch.
 
 defaults:
@@ -54,7 +55,8 @@ jobs:
         with:
           workflow-inputs: ${{ toJSON(inputs) }}
 
-  generate:
+  prepare-and-generate:
+    name: Generate ${{ inputs.doc-type }} documentation
     runs-on: ubuntu-22.04
     timeout-minutes: 5
     permissions:
@@ -71,13 +73,49 @@ jobs:
         with:
           ref: ${{ inputs.ref || env.BASE_BRANCH }}
 
-      - name: Generate Documentation for Multiple Files
+      - name: Collect YAML ans Markdown files
+        id: collect
+        env:
+          DOC_TYPE: ${{ inputs.doc-type }}
         run: |
           set -x
 
+
+          if [ "${DOC_TYPE}" == "workflow" ]; then
+            # Find all YAML files in the workflows directory
+            yaml_files="$(find .github/workflows -name '*.yml' -not -path '*internal*')"
+
+            # path/to/file1.yml → docs/file1.md
+            markdown_files="${yaml_files//.github\/workflows\//docs/}"
+            markdown_files="${markdown_files//.yml/.md}"
+
+          elif [ "${DOC_TYPE}" == "composite" ]; then
+            # Find all YAML files in the composite directory
+            yaml_files="$(find composite -name 'action.yml')"
+
+            # composite/path/to/file1/action.yml → docs/path/to/file1.md
+            markdown_files="${yaml_files//composite\//docs/}"
+            markdown_files="${markdown_files//\/action.yml/.md}"
+
+          else
+            echo "Error: Invalid doc-type value '${DOC_TYPE}'. It must be either 'workflow' or 'composite'."
+            exit 1
+          fi
+
+          # Output the YAML and Markdown files as JSON arrays
+          echo "YAML_FILES=$(echo "$yaml_files" | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_ENV"
+          echo "MARKDOWN_FILES=$(echo "$markdown_files" | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_ENV"
+          # echo "YAML_FILES=$(echo "${yaml_files[*]}" | jq -R -s -c 'split("\n")[:-1]')" >> "${GITHUB_ENV}"
+          # echo "MARKDOWN_FILES=$(echo "${markdown_files[*]}" | jq -R -s -c 'split("\n")[:-1]')" >> "${GITHUB_ENV}"
+
+      - name: Generate Documentation for Multiple Files
+        run: |
+          echo "::group::Generate Documentation for Multiple Files"
+          set -x
+
           # Use jq to parse the JSON array properly and remove unwanted characters
-          yaml_files_str=$(echo "${{ env.YAML_FILES }}" | jq -r '.[]')
-          markdown_files_str=$(echo "${{ env.MARKDOWN_FILES }}" | jq -r '.[]')
+          yaml_files_str=$(echo "${YAML_FILES}" | jq -r '.[]')
+          markdown_files_str=$(echo "${MARKDOWN_FILES}" | jq -r '.[]')
 
           echo "yaml_files_str: ${yaml_files_str}"
           echo "markdown_files_str: ${markdown_files_str}"
@@ -103,9 +141,7 @@ jobs:
             fi
             docker run --rm -v "$(pwd):/work" -w "/work" ghcr.io/tmknom/actdocs inject --sort --file "$markdown_file" "$yaml_file"
           done
-        env:
-          YAML_FILES: ${{ inputs.yaml-files }}
-          MARKDOWN_FILES: ${{ inputs.markdown-files }}
+          echo "::endgroup::"
 
       - name: Configure Git
         run: |
@@ -154,3 +190,104 @@ jobs:
         run: |
           set -x
           gh pr create --base "${BASE_BRANCH}" --head "${BRANCH}" --fill-first
+
+  # generate:
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 5
+  #   permissions:
+  #     contents: write
+  #     pull-requests: write
+  #   env:
+  #     BASE_BRANCH: ${{ github.event.repository.default_branch }}
+  #   outputs:
+  #     branch: ${{ steps.git-push.outputs.branch }}
+
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ inputs.ref || env.BASE_BRANCH }}
+
+  #     - name: Generate Documentation for Multiple Files
+  #       run: |
+  #         set -x
+
+  #         # Use jq to parse the JSON array properly and remove unwanted characters
+  #         yaml_files_str=$(echo "${{ env.YAML_FILES }}" | jq -r '.[]')
+  #         markdown_files_str=$(echo "${{ env.MARKDOWN_FILES }}" | jq -r '.[]')
+
+  #         echo "yaml_files_str: ${yaml_files_str}"
+  #         echo "markdown_files_str: ${markdown_files_str}"
+
+  #         # Convert newline-separated strings to arrays using mapfile
+  #         mapfile -t yaml_files <<< "$yaml_files_str"
+  #         mapfile -t markdown_files <<< "$markdown_files_str"
+
+  #         echo "YAML files array: ${yaml_files[*]}"
+  #         echo "Markdown files array: ${markdown_files[*]}"
+
+  #         for index in "${!yaml_files[@]}"; do
+  #           yaml_file=${yaml_files[index]}
+  #           markdown_file=${markdown_files[index]}
+
+  #           echo "Processing $yaml_file and $markdown_file"
+
+  #           # Check if the Markdown file exists, if not, create an empty file
+  #           if [ ! -f "$markdown_file" ]; then
+  #             echo "Creating empty Markdown file: $markdown_file"
+  #             mkdir -p "$(dirname "$markdown_file")"  # Ensure the directory exists
+  #             touch "$markdown_file"
+  #           fi
+  #           docker run --rm -v "$(pwd):/work" -w "/work" ghcr.io/tmknom/actdocs inject --sort --file "$markdown_file" "$yaml_file"
+  #         done
+  #       env:
+  #         YAML_FILES: ${{ inputs.yaml-files }}
+  #         MARKDOWN_FILES: ${{ inputs.markdown-files }}
+
+  #     - name: Configure Git
+  #       run: |
+  #         git config --global user.name "github-actions[bot]"
+  #         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+  #     - name: Git diff status
+  #       id: git-diff-status
+  #       run: |
+  #         echo "::group::Git diff status"
+  #         set -x
+  #         if [[ -z $(git status --porcelain) ]]; then
+  #           echo "No changes to commit."
+  #           echo "diff=false" >> "${GITHUB_OUTPUT}"
+  #         else
+  #           echo "Changes detected."
+  #           echo "diff=true" >> "${GITHUB_OUTPUT}"
+  #         fi
+  #         echo "::endgroup::"
+
+  #     - name: Git push
+  #       id: git-push
+  #       if: ${{steps.git-diff-status.outputs.diff == 'true'}}
+  #       env:
+  #         MESSAGE: ${{ inputs.commit-message }}
+  #       run: |
+  #         echo "::group::Git push"
+  #         set -x
+
+  #         branch="docs/$(date +%Y%m%d-%H%M%S)-${GITHUB_RUN_ID}"
+  #         log="Generated by ${GITHUB_WORKFLOW} workflow."
+  #         url="- ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
+
+  #         git switch -c "${branch}"
+  #         git add .
+  #         git commit -m "${MESSAGE}" -m "${log}" -m "${url}"
+  #         git push origin "${branch}"
+  #         echo "branch=${branch}" >> "${GITHUB_OUTPUT}"
+  #         echo "::endgroup::"
+
+  #     - name: Create PR
+  #       if: ${{ steps.git-push.outcome == 'success'}}
+  #       env:
+  #         BRANCH: ${{ steps.git-push.outputs.branch }}
+  #         GITHUB_TOKEN: ${{ github.token }}
+  #       run: |
+  #         set -x
+  #         gh pr create --base "${BASE_BRANCH}" --head "${BRANCH}" --fill-first
